WIP: CK.Ng.AspNet.Auth fails with a strange error.
TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function.
In the SourcedProviders constructor.